language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - cnpm install
#before_script:
 # - npm install -g gulp
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "kuleyu"
  - git config user.email "1402546930@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle
branches:
  only:
    - gh-pages-source
env:
 global:
   - GH_REF: github.com/kuleyu/hexolog.git
