language: node_js
node_js: stable
install:
- npm install -g cnpm --registry=https://registry.npm.taobao.org
- cnpm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "kuleyu"
- git config user.email "1402546930@qq.com"
- git add .
- git commit -m "Update docs"
- git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/kuleyu/hexolog.git
  - secure: Ky81LiRvryPuSbF9KtxvPlomWf7EABFR6ZoVIYUx2+ViUBf9xSqaRDikzN5cfy6r/gENKRgrHaHXSFH3AhnkPBNkm0HS+2+XrBEn5yVA+iS9llrWeKP6YSF6tj2lhsiXBZR7n5y6Ba9kmIvtp0LjqJ52ryvnmMwyw2GfyJk/6eSbGDle693LnoeVmIfoutHyIZ17aZidyG3t8GobTw50SAmVGf3ekTxxdjCB8MSpimSSG/fiN9UfrMkvGO1rafjLdPqVVbTrgmU5lvXRG1faW8fG/Z1ZUYHMvZELyNRz2db0nt7+kPtWSdQwYob4MtChqWvscz3uEw3WZtunIanluxVLqhlgaanLYS+ZfrfrSrgG2d70y+z0cxolGgdRnUpgOkIaMEM/aA0GU0T302ngZA0/Z/Xh6JmBSX8rakFLuaDFcXOJpRS6plihqiM2bnmSEVpQD0EQwdWSHVylwdLtTCXiXvwtASsAlHJ5+pSYe2kcxajFZi3wtK0fIUOoaRwyUl/TV3aC2tC/fI8P7SbFQPC+Qfd42oLjlhy52LMiYO+3iX32BkFM/eYrTQ0wm0mE1ZU8prPhx/1DLddvKxN3+HLO8R998H8xxtNpnHzGKzUyA8TJgs8bZCx3rZKyQOmsYCR7PMzzxPvHBUyr72fjzhJyEJCGKts+bNnMOR3Z/qc=
  - secure: ukrnbN5afnXyScbIUTR8v/EBMLsymjCZiZhzm61vQwLTKUM4rchWv9MCH4xVbEAA6C322r+LCsxmG4VIOoOq6tCbj3sMiAdMePT4j/WYUKn7XHVHar9T6Lyp6vLq13sHIsAZvjWAL0cKJtmtuvxLMK9PWjZpxOQiLsmcxgQz/3NlR/wnBLWML9EtVYXbgWSMlyHBdH50ujTmHPcpsza4rbSutSRpd/DU+sctIkFeEHaecx+dkpv8Vjh1v8N10PqH0ZYuTiNpOnFQkh8ZAa9uvrAeJPfXQercwto8eSR+gFG3Vdn1GIhrVm5MdGXkqvHRfaCQBBr59c1auQsjWKDv7YTieUEVezc2YxyAM+h15PsyEVYYtGMtB+xjaueQVM5H+ynppjqJszjsz6CikzOAor1PbNF3MFrAYHTukdbaxilctultCe3bWQR59+u73LB8dMYVAu2rECaa+BWNo8IwYFMBvJ6RcbJNgOLQ9I2QBwBsaHhB6k9dC+iOEEc2DdDk4ye1F2vmtQ5k0G5IqUE+MPGN2MsbYchkVyM9Xbcmdh3p4nlCp99PV2SmPy706HauEsb1lENzzMQKpjXMpgltM19kQbD3O2bqvJhEQ+9alRUjWBO2MoYufBc+1pfnUNovcnODq2TqG2RtdjOSCTZEqtKJ5+b0xjR/3no18UROKAg=
